---
# This task installs pre dependencies of xorg This is an example og tweaks and twerks
- name: Installing pre dependencies to use xorg-server
  pacman:
    name: libglvnd
    state: present
  when: ansible_os_family == "Archlinux"

- name: "openknowit_3nodekube | main |  "
  copy:
    src: setup3nodekube_debian.sh
    dest: /ust/local/bin/setup3nodekube_debian.sh
    mode: 0755
    owner: root
    state: present
  when: ansible_os_family == "Debian"
  become: true